version: '4'
services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: seleniarm/node-chromium:latest
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub-new
      - HUB_PORT=4444
    depends_on:
      - selenium-hub

  firefox:
    image: seleniarm/node-firefox:latest
    container_name: firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub




