on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:2.10.0:report

      - name: List Allure report directory
        run: ls -al target/site/allure-maven-plugin/

      - name: Build Docker image
        run: docker build -t my-test-image .

      - name: Run tests in Docker container
        run: |
          docker run --name test-container my-test-image mvn test
          docker cp test-container:/app/target/allure-results ./target/allure-results
          docker rm test-container

      - name: Generate Allure Report from Docker
        run: mvn io.qameta.allure:allure-maven:2.10.0:report -f ./target/allure-results

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
