name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, MacBook-Air]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Run tests
        run: docker run my-java-app
