name: Sync Local Branch with Remote Master

on:
  pull_request:
    types: [closed]

jobs:
  sync-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch updates from remote
        run: |
          git fetch origin

      - name: Merge remote master into local master
        run: |
          git merge origin/master

      - name: Push changes to remote
        run: |
          git push origin master


