name: Sync Local Branch with Remote Master

on:
  pull_request:
    types: [closed]

jobs:
  sync-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch updates from remote
        run: |
          git fetch origin

      - name: Merge remote master into local master
        run: |
          git merge origin/master

      - name: Push changes to remote
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git push origin master


